name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Upgrade pip
        run: python -m pip install -U pip wheel
      - name: Install Torch (CPU)
        run: python -m pip install torch>=2.2.0
      - name: Install PyG deps (CPU wheels)
        run: |
          python -m pip install --index-url https://data.pyg.org/whl/torch-2.2.0+cpu torch-scatter torch-sparse torch-cluster
          python -m pip install torch-geometric
      - name: Install project deps
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -e .
      - name: Run tests
        run: pytest -q
